# Teste da rota GET /eventos
GET http://localhost:3000/eventos
Accept: application/json

###

# Teste da rota GET /eventos/:id
GET http://localhost:3000/eventos/1
Accept: application/json

###

# Teste da rota POST /eventos
POST http://localhost:3000/eventos
Content-Type: application/json

{
  "titulo": "HP da Stef",
  "descricao": "Festa a fantasia muito top",
  "local": "Casa da Stef",
  "data_hora_inicio": "20:00",
  "data_hora_fim": "07:00",
  "limite_convidados": "500"
}

###

# Teste da rota PUT /eventos/:id
PUT http://localhost:3000/eventos/1
Content-Type: application/json

{
  "titulo": "HP da Stef",
  "descricao": "Festa a fantasia muito top",
  "local": "Casa da Stef",
  "data_hora_inicio": "20:00",
  "data_hora_fim": "07:00",
  "limite_convidados": "500"
}

###

# Teste da rota DELETE /eventos/:id
DELETE http://localhost:3000/eventos/1
Accept: application/json


###

# Teste da rota PUT /usuarios/:id/senha
PUT http://localhost:3000/usuarios/4/senha
Content-Type: application/json

{
  "senha": "222222"
}

###

# Teste da rota PUT /usuarios/:id/nome
PUT http://localhost:3000/usuarios/4/nome
Content-Type: application/json

{
  "nome": "Matheuz"
}

###

# Teste da rota PUT /usuarios/:id/email
PUT http://localhost:3000/usuarios/4/email
Content-Type: application/json

{
  "email": "matheus@gmail.com"
}

###

# Teste da rota PUT /usuarios/:id/apelido
PUT http://localhost:3000/usuarios/4/apelido
Content-Type: application/json

{
  "apelido_eventual": "ADMIN"
}

###

# Teste da rota GET /usuarios
GET http://localhost:3000/usuarios
Content-Type: application/json

###

# Teste da rota GET /usuarios/:id
GET http://localhost:3000/usuarios/4
Content-Type: application/json
