# Teste da rota GET /eventos
GET http://localhost:3000/eventos
Accept: application/json

###

# Teste da rota GET /eventos/:id
GET http://localhost:3000/eventos/2
Accept: application/json

###

# Teste da rota POST /eventos
POST http://localhost:3000/eventos
Content-Type: application/json

{
  "titulo": "HP NO THEUS",
  "descricao": "Fresenha basica",
  "local": "Casa do theus",
  "data_hora_inicio": "20:00",
  "data_hora_fim": "07:00",
  "limite_convidados": "500"
}

###

# Teste da rota PUT /eventos/:id
PUT http://localhost:3000/eventos/6
Content-Type: application/json

{
  "titulo": "HP NO THEUS",
  "descricao": "Resenha basicaaa",
  "local": "Casa do theus",
  "data_hora_inicio": "20:00",
  "data_hora_fim": "07:00",
  "limite_convidados": "500"
}

###

# Teste da rota DELETE /eventos/:id
DELETE http://localhost:3000/eventos/6
Accept: application/json

###

# Teste da rota PUT /usuarios/:id/senha
PUT http://localhost:3000/usuarios/4/senha
Content-Type: application/json

{
  "senha": "222222"
}

###

# Teste da rota PUT /usuarios/:id/nome
PUT http://localhost:3000/usuarios/4/nome
Content-Type: application/json

{
  "nome": "Matheus"
}

###

# Teste da rota PUT /usuarios/:id/email
PUT http://localhost:3000/usuarios/4/email
Content-Type: application/json

{
  "email": "matheuz@gmail.com"
}

###

# Teste da rota PUT /usuarios/:id/apelido
PUT http://localhost:3000/usuarios/4/apelido
Content-Type: application/json

{
  "apelido_eventual": "ADMN"
}

###

# Teste da rota GET /usuarios
GET http://localhost:3000/usuarios
Content-Type: application/json

###

# Teste da rota GET /usuarios/:id
GET http://localhost:3000/usuarios/4
Content-Type: application/json

###

### GET TODOS ORGANIZADORES
GET http://localhost:3000/organizadores

### GET ORGANIZADORES POR USUÁRIO
GET http://localhost:3000/organizadores/usuario/4

### GET ORGANIZADORES POR EVENTO
GET http://localhost:3000/organizadores/evento/3

### POST NOVO ORGANIZADOR
POST http://localhost:3000/organizadores
Content-Type: application/json

{
  "papel": "coordenador",
  "id_usuario": 4,
  "id_evento": 3
}

### PUT - ALTERAR PAPEL
PUT http://localhost:3000/organizadores/4/3
Content-Type: application/json

{
  "papel": "admim"
}

### DELETE - REMOVER ORGANIZADOR
DELETE http://localhost:3000/organizadores/4/3
