# Teste da rota GET /eventos
GET http://localhost:3000/eventos
Accept: application/json

###

# Teste da rota GET /eventos/:id
GET http://localhost:3000/eventos/3
Accept: application/json

###

# Teste da rota POST /eventos
POST http://localhost:3000/eventos
Content-Type: application/json

{
  "titulo": "HP NA DUDA",
  "descricao": "Vai todo mundo",
  "local": "Share - 19",
  "data_hora_inicio": "2025-06-02T13:15:00.000Z",
  "data_hora_fim": "2025-06-03T13:15:00.000Z",
  "limite_convidados": "500"
}

###

# Teste da rota PUT /eventos/:id
PUT http://localhost:3000/eventos/7
Content-Type: application/json

{
  "titulo": "HP NA DUDA",
  "descricao": "Vai todo mundo",
  "local": "Share - 19",
  "data_hora_inicio": "20:00",
  "data_hora_fim": "07:00",
  "limite_convidados": "10"
}

###

# Teste da rota DELETE /eventos/:id
DELETE http://localhost:3000/eventos/3
Accept: application/json

###

# Teste da rota POST /usuarios

POST http://localhost:3000/usuarios
Content-Type: application/json

{ 
  "nome": "Duda",
  "email": "duda2@gmail.com",
  "senha": "22222"
}

###

# Teste da rota PUT /usuarios/:id/senha
PUT http://localhost:3000/usuarios/5/senha
Content-Type: application/json

{
  "senha": "3333"
}

###

# Teste da rota PUT /usuarios/:id/nome
PUT http://localhost:3000/usuarios/5/nome
Content-Type: application/json

{
  "nome": "dudex"
}

###

# Teste da rota PUT /usuarios/:id/email
PUT http://localhost:3000/usuarios/5/email
Content-Type: application/json

{
  "email": "duda@gmail.com"
}

###

# Teste da rota PUT /usuarios/:id/apelido
PUT http://localhost:3000/usuarios/5/apelido
Content-Type: application/json

{
  "apelido_eventual": "ORGANIZADORA"
}

###

# Teste da rota GET /usuarios
GET http://localhost:3000/usuarios
Content-Type: application/json

###

# Teste da rota GET /usuarios/:id
GET http://localhost:3000/usuarios/5
Content-Type: application/json

###

### GET TODOS ORGANIZADORES
GET http://localhost:3000/organizadores

### GET ORGANIZADORES POR USUÁRIO
GET http://localhost:3000/organizadores/usuario/4

### GET ORGANIZADORES POR EVENTO
GET http://localhost:3000/organizadores/evento/3

### POST NOVO ORGANIZADOR
POST http://localhost:3000/organizadores
Content-Type: application/json

{
  "papel": "coordenador",
  "id_usuario": 5,
  "id_evento": 5
}

### PUT - ALTERAR PAPEL
PUT http://localhost:3000/organizadores/5/5
Content-Type: application/json

{
  "papel": "admim"
}

### DELETE - REMOVER ORGANIZADOR
DELETE http://localhost:3000/organizadores/5/5

### GET todos os convidados de um evento
GET http://localhost:3000/eventos/3/convidados
Accept: application/json

###

### GET todos os confirmados de um evento
GET http://localhost:3000/eventos/3/confirmados
Accept: application/json

###

### POST convidar usuário para evento
POST http://localhost:3000/eventos/8/convidados
Content-Type: application/json

{
  "id_convidado": 1
}

###

### PUT confirmar presença do convidado no evento
PUT http://localhost:3000/eventos/3/convidados/5/confirmar
Accept: application/json

###

### DELETE remover convidado do evento
DELETE http://localhost:3000/eventos/3/convidados/5
Accept: application/json

###

### GET - Todas as mensagens de um evento
GET http://localhost:3000/eventos/3/mensagens
Accept: application/json

###

### POST - Nova mensagem em um evento
POST http://localhost:3000/eventos/3/mensagens
Content-Type: application/json

{
  "id_usuario": 5,
  "conteudo": "Vai ser top!"
}

###

### DELETE - Remover uma mensagem
DELETE http://localhost:3000/eventos/3/mensagens/5
Accept: application/json
